// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/account" | "/api/admin/actions" | "/api/admin/auth/login" | "/api/admin/auth/logout" | "/api/admin/conversations" | "/api/admin/export" | "/api/admin/overview" | "/api/admin/session" | "/api/auth/forgot-password" | "/api/auth/google/callback" | "/api/auth/google/start" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/providers" | "/api/auth/register" | "/api/auth/reset-password" | "/api/billing/cancel" | "/api/billing/checkout" | "/api/billing/portal" | "/api/conversations" | "/api/db" | "/api/events" | "/api/link-preview" | "/api/presence" | "/api/push/public-key" | "/api/push/subscribe" | "/api/release/announce" | "/api/release/current" | "/api/session" | "/api/stripe/webhook"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/account": {}
  "/api/admin/actions": {}
  "/api/admin/auth/login": {}
  "/api/admin/auth/logout": {}
  "/api/admin/conversations": {}
  "/api/admin/export": {}
  "/api/admin/overview": {}
  "/api/admin/session": {}
  "/api/auth/forgot-password": {}
  "/api/auth/google/callback": {}
  "/api/auth/google/start": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/providers": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/billing/cancel": {}
  "/api/billing/checkout": {}
  "/api/billing/portal": {}
  "/api/conversations": {}
  "/api/db": {}
  "/api/events": {}
  "/api/link-preview": {}
  "/api/presence": {}
  "/api/push/public-key": {}
  "/api/push/subscribe": {}
  "/api/release/announce": {}
  "/api/release/current": {}
  "/api/session": {}
  "/api/stripe/webhook": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
